server:
   port: 9924

#eureka:
#   client:
#      service-url:
#         defaultZone: http://localhost:9320/eureka
#      register-with-eureka: true
#      fetch-registry: true #本地缓存服务

spring:
   profiles:
      active: dev
   messages:
      basename: i18n/messages
      encoding: UTF-8
   application:
      name: idCenter
   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 1000  # 连接超时时间（毫秒）


logging:
   config: classpath:logback-spring.xml

zookeeper:
   host: 127.0.0.1:2181
#management:
#   security:
#      enabled: false




